# Generated by Django 2.1.4 on 2018-12-06 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Extcoeff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wave', models.FloatField()),
                ('coeff', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('thickness', models.FloatField()),
                ('layer_sequence', models.IntegerField(max_length=2, null=True)),
                ('optical_designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OptimalFilmDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_1', models.CharField(max_length=50)),
                ('material_1', models.CharField(max_length=50)),
                ('type_2', models.CharField(max_length=50, null=True)),
                ('material_2', models.CharField(max_length=50, null=True)),
                ('type_3', models.CharField(max_length=50, null=True)),
                ('material_3', models.CharField(max_length=50, null=True)),
                ('type_4', models.CharField(max_length=50, null=True)),
                ('material_4', models.CharField(max_length=50, null=True)),
                ('type_substrate', models.CharField(max_length=50, null=True)),
                ('material_substrate', models.CharField(max_length=50, null=True)),
                ('wave_min', models.FloatField()),
                ('wave_max', models.FloatField()),
                ('max_thickness', models.FloatField()),
                ('filmtype', models.CharField(choices=[('Antireflection', 'Minimize the reflection'), ('Highreflection', 'Maximize the reflection')], max_length=50)),
                ('optical_designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('pageid', models.IntegerField(primary_key=True, serialize=False)),
                ('shelf', models.CharField(choices=[('main', 'some common inorganic materials'), ('organic', 'organic materials'), ('glass', 'glass'), ('other', 'miscellaneous and composite materials'), ('3d', 'data for fun')], max_length=10)),
                ('book', models.CharField(max_length=30)),
                ('page', models.CharField(max_length=50)),
                ('filepath', models.CharField(blank=True, max_length=200, null=True)),
                ('hasrefractive', models.BooleanField()),
                ('hasextinction', models.BooleanField()),
                ('rangeMin', models.FloatField()),
                ('rangeMax', models.FloatField()),
                ('points', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='Refractiveindex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wave', models.FloatField()),
                ('refindex', models.FloatField()),
                ('pageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optical_parameter.Pages')),
            ],
        ),
        migrations.AlterOrderWithRespectTo(
            name='optimalfilmdesign',
            order_with_respect_to='type_substrate',
        ),
        migrations.AlterOrderWithRespectTo(
            name='film',
            order_with_respect_to='layer_sequence',
        ),
        migrations.AddField(
            model_name='extcoeff',
            name='pageid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optical_parameter.Pages'),
        ),
    ]
