# Generated by Django 2.0.7 on 2018-09-02 02:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extcoeff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wave', models.FloatField()),
                ('coeff', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('pageid', models.IntegerField(primary_key=True, serialize=False)),
                ('shelf', models.CharField(choices=[('main', 'some common inorganic materials'), ('organic', 'organic materials'), ('glass', 'glass'), ('other', 'miscellaneous and composite materials'), ('3d', 'data for fun')], max_length=10)),
                ('book', models.CharField(max_length=30)),
                ('page', models.CharField(max_length=50)),
                ('filepath', models.CharField(max_length=200)),
                ('hasrefractive', models.BooleanField()),
                ('hasextinction', models.BooleanField()),
                ('rangeMin', models.FloatField()),
                ('rangeMax', models.FloatField()),
                ('points', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('insert_user', models.CharField(default='admin', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Refractiveindex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wave', models.FloatField()),
                ('refindex', models.FloatField()),
                ('pageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optical_parameter.Pages')),
            ],
        ),
        migrations.AddField(
            model_name='extcoeff',
            name='pageid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optical_parameter.Pages'),
        ),
    ]
