# Generated by Django 2.0.7 on 2018-09-02 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optical_parameter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='insert_user',
        ),
    ]
