# Generated by Django 2.0.7 on 2018-09-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optical_parameter', '0002_auto_20180902_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('main', 'some common inorganic materials'), ('organic', 'organic materials'), ('glass', 'glass'), ('other', 'miscellaneous and composite materials'), ('3d', 'data for fun')], max_length=10)),
                ('material', models.CharField(max_length=30)),
                ('resource', models.CharField(max_length=50)),
                ('thickness', models.FloatField()),
                ('layer_sequence', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='pages',
            options={'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterField(
            model_name='pages',
            name='filepath',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
