# Generated by Django 2.0.7 on 2018-09-04 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optical_parameter', '0003_auto_20180904_1650'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Film',
        ),
    ]
