# Generated by Django 2.0.7 on 2018-09-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optical_parameter', '0005_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='type',
            field=models.CharField(choices=[('main', 'common inorganic materials'), ('organic', 'organic materials'), ('glass', 'glass'), ('other', 'miscellaneous and composite materials')], max_length=10),
        ),
    ]
