# Generated by Django 2.0.7 on 2018-09-05 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optical_parameter', '0006_auto_20180904_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='resource',
        ),
    ]
