# Generated by Django 2.0.7 on 2018-09-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optical_parameter', '0007_remove_film_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFilm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('material', models.CharField(max_length=30)),
                ('thickness', models.FloatField()),
                ('layer_sequence', models.IntegerField()),
            ],
        ),
    ]
