# Generated by Django 2.0.7 on 2018-09-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optical_parameter', '0008_testfilm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testfilm',
            name='layer_sequence',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='testfilm',
            name='material',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='testfilm',
            name='thickness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='testfilm',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
