# Generated by Django 2.0.7 on 2018-09-05 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optical_parameter', '0010_auto_20180905_1707'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestFilm',
        ),
    ]
