# Generated by Django 2.0.7 on 2018-09-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optical_parameter', '0011_delete_testfilm'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFilm',
            fields=[
                ('type', models.CharField(max_length=50, null=True)),
                ('material', models.CharField(max_length=50, null=True)),
                ('thickness', models.FloatField(null=True)),
                ('layer_sequence', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
