# Generated by Django 2.0.7 on 2018-09-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optical_parameter', '0012_testfilm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestFilm',
        ),
        migrations.RemoveField(
            model_name='film',
            name='id',
        ),
        migrations.AlterField(
            model_name='film',
            name='layer_sequence',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='film',
            name='material',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='thickness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
